group: catalog
apiVersion: v1alpha1
kind: AccessControlList
name: edit-only-access
title: edit-only-access
metadata:
  scope:
    kind: Asset
    name: aj-asset-1-cli
spec:
  rules:
    - access:
        - level: scope
          allowWrite: true
          allowDelete: false
          allowCreateScoped: false
  subjects:
    - id: 89eff307-950f-4939-8862-51d3e8c09a38
      type: team
    - id: d1051ac4-49cc-4fe5-83a6-b91e7deedaeb
      type: team
