group: catalog
apiVersion: v1alpha1
kind: Asset
title: "{{assets.[].name}}"
name: "{{func.generate_name}}"
owner:
  type: team
  id: "{{func.lookup_team_id}}"
  teamName: "{{assets.[].owner.teamName}}"
spec:
  type: API
  # categories:
    # - aj-category
  description: "{{assets.[].description}}"
access:
  approval: manual
state: draft